- docs/introduction/Motivation.md
> 校对 Motivation

- docs/introduction/Ecosystem.md
- docs/introduction/ThreePrinciples.md
校对 ThreePrinciples 和 Ecosystem 两章，其中 ecosystem 增加一些作者补充的内容
> 校对 ThreePrinciples 和 Ecosystem

- docs/advanced/ExampleRedditAPI.md
- docs/recipes/MigratingToRedux.md
> [WIP]翻译 ExampleRedditAPI.html & MigratingToRedux.html

- contributes.md
- docs/recipes/WritingTests.md
> Translated: 写测试

- docs/introduction/PriorArt.md
> 翻译 prior art

- contributes.md
Reverts camsong/redux-in-chinese#12
> Revert "add contributor to ReducingBoilerplate"

- docs/recipes/MigratingToRedux.md
Proofread `docs/recipes/MigratingToRedux.md`
> Proofread docs/recipes/MigratingToRedux.md

- docs/advanced/AsyncFlow.md
Proofread docs/advanced/AsyncFlow.md
> Proofread docs/advanced/AsyncFlow.md

- README.md
- contributes.md
- docs/advanced/Middleware.md
translate docs/advanced/Middleware.md
> translate docs/advanced/Middleware.md

- docs/recipes/README.md
> keep the original

- docs/api/applyMiddleware.md
我这两天在外面翻的，发现你已经翻完了⊙﹏⊙b汗。
简单校对了一下，有些不太通顺的用了我翻的版本，供参考，如果觉得没有原来的好拒绝也没问题。
> Proofread docs/api/applyMiddleware.md

- docs/recipes/ServerRendering.md
> modified docs/recipes/ServerRendering.md

- contributes.md
- docs/introduction/Motivation.md
- docs/introduction/PriorArt.md
- docs/introduction/ThreePrinciples.md
Motivation, Three Principles, Prior Art
> take proofread of introduction

- contributes.md
- docs/basics/Actions.md
- docs/introduction/Examples.md
根据 redux 官方文档增加了3行新代码。以及行号对齐的小调整。
> small update to basics/Actions

- CNAME
- package.json
> add CNAME cn.reduxjs.com

- docs/introduction/Ecosystem.md
- docs/introduction/PriorArt.md
> 更正了 introduction/ 中所有的单复数问题

- docs/recipes/ImplementingUndoHistory.md
这一句：
> There are no multiple models—just a state subtree that you want to keep track of.
中的 models—just 不知如何理解，综合上下文似乎是说 Redux 没有传统 MVC 那样多重的 model，需要由 controller 决定将哪些映射到 view 上面。Redux 的 model 是严格唯一的，因此追踪起来很容易。
另外，Undo 和 Redo 我纠结了好久要不要翻译，最终还是统一翻译成 撤消 和 重做。
> translate docs/recipes/ImplementingUndoHistory.md

- docs/react-redux/README.md
- docs/react-redux/troubleshooting.md
> translate docs/react-redux/README.md

- docs/react-redux/quick-start.md
@camsong  Done. 有部分翻译不是很准确，望斧正。
> translated quick-start.md and fixed #48

- docs/react-redux/troubleshooting.md
> translated troubleshooting.md and fixed #49

- docs/react-redux/api.md
> Updated the translation. 修饰 -> 包装，属性 -> props

- docs/basics/Reducers.md
1. 到现在为步 --> 到现在为止
2. switch-case 缩进的调整
> fixed little typo and indent issue

- docs/advanced/AsyncActions.md
- docs/advanced/AsyncFlow.md
- docs/advanced/ExampleRedditAPI.md
- docs/advanced/Middleware.md
> Proofread docs/advanced and fixed #60

- docs/basics/Actions.md
- docs/basics/Reducers.md
- docs/basics/Store.md
> Proofread docs/basic/Actions+Reducers+Store

- docs/recipes/ComputingDerivedData.md
- docs/recipes/ImplementingUndoHistory.md
- docs/recipes/MigratingToRedux.md
- docs/recipes/ReducingBoilerplate.md
- docs/recipes/ServerRendering.md
- docs/recipes/WritingTests.md
proofread recipes done
更新了新增代码。对一些小错误进行了修改。
> proofread recipes done

- docs/introduction/Ecosystem.md
Sync for [Ecosystem.md](https://github.com/rackt/redux/blob/master/docs/introduction/Ecosystem.md). Welcome to review.
> proofread and sync origin doc for Ecosystem.md

- docs/basics/ExampleTodoList.md
少写了一条语句
export default connect(select)(App)
注释多了一行
> 2.6 containers/App.js 一节末尾改正建议

- docs/advanced/AsyncActions.md
在第三节（设计 state 结构）的第一段里，「在写同步代码的时候」应该是「在写异
步代码的时候」
> 修正 3.1.异步 Action 一文字错误

- docs/Glossary.md
- docs/recipes/ReducingBoilerplate.md
> 统一将 constant(s) 翻译为「常量」

- docs/basics/Store.md
> 修订了unsubscribe函数来源的注释

- docs/basics/UsageWithReact.md
Reverts camsong/redux-in-chinese#101
> Revert "Update UsageWithReact.md"

- docs/advanced/AsyncActions.md
- docs/basics/Reducers.md
> update AsyncActions.md and Reducers.md

- docs/recipes/ReducingBoilerplate.md
> 将可串行改为可序列化

- docs/advanced/Middleware.md
the function of patchStoreToAddLogging was wrong
> fix the doc

- docs/basics/Actions.md
see https://github.com/reactjs/redux/commit/b0763b126b497233d37193c95488855bdf50ff60
> Clarify action creators don't need to be pure

- docs/introduction/Ecosystem.md
- docs/introduction/Examples.md
- docs/introduction/PriorArt.md
- docs/introduction/ThreePrinciples.md
> Introduction Updated

- docs/basics/Actions.md
- docs/basics/Store.md
将 COMPLETE_TODO 修改成和官网一样的 TOGGLE_TODO
> 修改2.1节中的小错误

- docs/api/createStore.md
add description for the 3rd param enhancer of createStore
> desc 3rd param enhancer of createStore

- docs/recipes/ReducingBoilerplate.md
> fix code bug

- docs/recipes/ReducingBoilerplate.md
> typo error

- docs/recipes/WritingTests.md
> 文档同步：【技巧-编写测试】

- docs/README.md
- docs/recipes/reducers/InitializingState.md
please review.
由于是新文章，为了方便 review 我把英文原文也贴上了。
> Translate InitializingState.md

- docs/recipes/StructuringReducers.md
> Translate StructuringReducers.md

- docs/api/applyMiddleware.md
sync docs/api/applyMiddleware.md
> sync docs/api/applyMiddleware.md

- docs/api/combineReducers.md
https://github.com/camsong/redux-in-chinese/issues/193
> sync doc translate：[API-combineReducers]

- docs/README.md
- docs/recipes/reducers/PrerequisiteConcepts.md
> Translate PrerequisiteConceptes.md

- docs/basics/Store.md
Reverts camsong/redux-in-chinese#214
> Revert "Update Store.md"

- docs/recipes/ImplementingUndoHistory.md
> sync ImplementingUndoHistory.md

- docs/recipes/reducers/BeyondCombineReducers.md
> add BeyondCombineReducers.md

- docs/recipes/reducers/ImmutableUpdatePatterns.md
> add Immutable Update Patterns

- docs/recipes/reducers/UpdatingNormalizedData.md
https://github.com/camsong/redux-in-chinese/issues/183
> sync doc translate UpdatingNormalizedData.md

- README.md
Signed-off-by: Zhao Junwang <zhjwpku@gmail.com>
> fix typo and add a line that not translated

- docs/basics/Reducers.md
> add some missing part

- docs/react-redux/api.md
Believe there is a little error in document.
But I'm not sure since not familiar with react-redux
> Update react-redux api

- docs/basics/Store.md
> 文档同步(基础-Store)

- docs/api/combineReducers.md
主要是 combineReducers() 返回 state 结构的更新，原文档此次文档更新幅度较小
> 更新 API-combineReducers #275

- docs/api/createStore.md
修改1 更新代码格式
- 原文只更新了代码格式： https://github.com/reactjs/redux/commit/9867ec591432201a73cc447119e7b874e86e2fc1#diff-15feaeca2f0fa6ba115f73e179754357L26
修改2 修改原译文（个人建议）
- 原翻译：如果第一个参数也就是传入的 state 如果是 `undefined` 的话
- 修改后：如果第一个参数也就是传入的 state 是 `undefined` 的话
> createStore: improve formatting and translation

- docs/FAQ.md
- docs/api/compose.md
> updated FAQ.md and compose.md

- docs/faq/DesignDecisions.md
- docs/faq/ImmutableData.md
- docs/recipes/UsingImmutableJS.md
* 添加了新增的文档
* 翻译了 UsingImmutableJS.md
详见 #308
> update: tranlsate docs/recipes/UsingImmutableJS.md into Chinese

- docs/advanced/UsageWithReactRouter.md
原文：https://github.com/reactjs/redux/blob/master/docs/advanced/UsageWithReactRouter.md
译文：https://github.com/camsong/redux-in-chinese/blob/master/docs/advanced/UsageWithReactRouter.md
> 文档同步：【高级-搭配 React Router】

- docs/faq/DesignDecisions.md
> Add translation: faq/DesignDecisions

- docs/react-redux/troubleshooting.md
> update react-redux/troubleshooting.md, fixes  #265

- docs/advanced/Middleware.md
参见 #270 
同步了原文中以下 commit
- [704f711](https://github.com/reactjs/redux/commit/827b627c4011f14ff541db6d1ec162f8e12484fa#diff-46a3cc23334de21b41088e224f47eaf9)
- [827b627](https://github.com/reactjs/redux/commit/827b627c4011f14ff541db6d1ec162f8e12484fa#diff-46a3cc23334de21b41088e224f47eaf9)
- [dd165df](https://github.com/reactjs/redux/commit/dd165dfc6878bc9aa6045bc1fc1943640a23e5e8#diff-46a3cc23334de21b41088e224f47eaf9)
- [f35e98c](https://github.com/reactjs/redux/commit/f35e98ce29fe327096bcb7db4e65d76872fc2bf1#diff-46a3cc23334de21b41088e224f47eaf9)
- [34cfc89](https://github.com/reactjs/redux/commit/34cfc8937e19941892a6a429ab886daa6088b626#diff-46a3cc23334de21b41088e224f47eaf9)
> Update translation: advanced/Middleware

- docs/basics/DataFlow.md
> update  docs/basics/DataFlow.md #279

- docs/faq/DesignDecisions.md
> spelling  error in DesignDecisions.md

- docs/recipes/reducers/InitializingState.md
添加对 [Initializing State](https://redux.js.org/recipes/structuring-reducers/initializing-state) 一节的翻译。
> translate 「initializingState.md」

- docs/faq/Actions.md
- docs/introduction/PriorArt.md
Update docs/faq/Actions.md
Update docs/introduction/PriorArt.md
> Update PriorArt.md and Actions.md

- docs/advanced/NextSteps.md
> Add translation: advanced/NestSteps

- SUMMARY.md
- docs/recipes/CodeSplitting.md
- docs/recipes/README.md
原文：[CodeSplitting](https://github.com/reduxjs/redux/blob/master/docs/recipes/CodeSplitting.md)
> Add docs/recipes/CodeSplitting.md

- SUMMARY.md
- docs/advanced/README.md
- docs/advanced/UsageWithTypescript.md
- docs/recipes/UsingImmutableJS.md
原文：[UsageWithTypescript](https://github.com/reduxjs/redux/blob/master/docs/advanced/UsageWithTypescript.md)
> add docs/advanced/UsageWithTypescript.md

- docs/advanced/UsageWithReactRouter.md
> Fix react router link

- docs/introduction/GettingStarted.md
- docs/tutorials/essentials/part-3-data-flow.md
- docs/tutorials/essentials/part-5-async-logic.md
close #406 
close #407
close #408
close #410
> feat: update part-5 async logic

- docs/tutorials/fundamentals/part-7-standard-patterns.md
> feat: Transtion of Redux Fundamentals/standard-patterns

- docs/tutorials/fundamentals/part-2-concepts-data-flow.md
> feat: Transtion of Redux Fundamentals/concepts-data-flow

- docs/tutorials/fundamentals/part-1-overview.md
> feat: Translation of Redux Fundamentals/Redux Overview

- docs/tutorials/essentials/part-2-app-structure.md
> fix: tutorials/essentials spelling (#432)

- docs/tutorials/quick-start.md
> [feat](quick-start): 你将学习到什么

- docs/tutorials/essentials/part-6-performance-normalization.md
notificationsSlice中fetchNotifications返回值应使用response.data
> fix: 点击Refresh Notifications,代码运行错误

- docs/tutorials/fundamentals/part-6-async-logic.md
> feat: translate docs/tutorials/fundamentals/part-6-async-logic.md

- docs/usage/WritingTests.mdx
translate the redux testing doc parts.
> docs: translate part of writing test

- docs/tutorials/fundamentals/part-5-ui-and-react.md
> feat: translate docs/tutorials/fundamentals/part-5-ui-and-react.md

- docs/tutorials/fundamentals/part-7-standard-patterns.md
> feat: translate docs/tutorials/fundamentals/part-7-standard-patterns.md

- docs/tutorials/fundamentals/part-8-modern-redux.md
> feat: translate docs/tutorials/fundamentals/part-8-modern-redux.md

- docs/usage/deriving-data-selectors.md
完成  docs/usage/deriving-data-selectors.md
> complete: docs/usage/deriving-data-selectors.md

- docs/introduction/LearningResources.md
> fix: Delete excess text

- docs/tutorials/essentials/part-5-async-logic.md
> 修复 tips 标签闭合问题
